//
//  ShopInformationViewController.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/09.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import WebKit

protocol ShopInformationDisplayLogic: class {
    func displaySomething(viewModel: ShopInformation.Load.ViewModel)
}

class ShopInformationViewController: UIViewController, ShopInformationDisplayLogic {
    var interactor: ShopInformationBusinessLogic?
    var router: (NSObjectProtocol & ShopInformationRoutingLogic & ShopInformationDataPassing)?
    
    @IBOutlet weak var webView: WKWebView!
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ShopInformationInteractor()
        let presenter = ShopInformationPresenter()
        let router = ShopInformationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        loadShopInformation()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func loadShopInformation() {
        let request = ShopInformation.Load.Request()
        interactor?.loadShopInformation(request: request)
    }
    
    func displaySomething(viewModel: ShopInformation.Load.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}

extension ShopInformationViewController: WKUIDelegate {
    
}

extension ShopInformationViewController: WKNavigationDelegate {
    
}
