//
//  RestaurantInforamtionPresenter.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/09.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RestaurantInformationPresentationLogic {
    func presentRestaurantInformation(response: RestaurantInformation.Load.Response)
}

class RestaurantInformationPresenter: RestaurantInformationPresentationLogic {
    weak var viewController: RestaurantInformationDisplayLogic?
    
    // MARK: Do something
    
    func presentRestaurantInformation(response: RestaurantInformation.Load.Response) {
        let viewModel = RestaurantInformation.Load.ViewModel(url: response.url)
        viewController?.displayRestaurantInformation(viewModel: viewModel)
    }
}
