//
//  RestaurantInformationInteractor.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/09.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RestaurantInformationBusinessLogic {
    func loadRestaurantInformation(request: RestaurantInformation.Load.Request)
}

protocol RestaurantInformationDataStore {
    var urlString: String { get set }
}

class RestaurantInformationInteractor: RestaurantInformationBusinessLogic, RestaurantInformationDataStore {
    var presenter: RestaurantInformationPresentationLogic?
    var worker: RestaurantInformationWorker?
    var urlString: String = ""
    
    // MARK: Do something
    
    func loadRestaurantInformation(request: RestaurantInformation.Load.Request) {
        let response = RestaurantInformation.Load.Response(url: urlString)
        presenter?.presentRestaurantInformation(response: response)
    }
}
