//
//  RestaurantInformationModels.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/09.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RestaurantInformation {
    // MARK: Use cases
    
    enum Load {
        struct Request {
        }
        struct Response {
            var url: String
        }
        struct ViewModel {
            var url: String
        }
    }
}
