//
//  ShopInformationInteractor.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/09.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShopInformationBusinessLogic {
    func doSomething(request: ShopInformation.Something.Request)
}

protocol ShopInformationDataStore {
    //var name: String { get set }
}

class ShopInformationInteractor: ShopInformationBusinessLogic, ShopInformationDataStore {
    var presenter: ShopInformationPresentationLogic?
    var worker: ShopInformationWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ShopInformation.Something.Request) {
        worker = ShopInformationWorker()
        worker?.doSomeWork()
        
        let response = ShopInformation.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
