//
//  ShopInforamtionPresenter.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/09.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShopInformationPresentationLogic {
    func presentSomething(response: ShopInformation.Something.Response)
}

class ShopInformationPresenter: ShopInformationPresentationLogic {
    weak var viewController: ShopInformationDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ShopInformation.Something.Response) {
        let viewModel = ShopInformation.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
