//
//  MapInteractor.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/07.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapBusinessLogic {
    func initMapView(request: Map.Init.Request)
    func searchRestaurants(request: Map.Search.Request)
    func fetchRestaurantInformation(request: Map.Fetch.Request)
}

protocol MapDataStore {
    var urlString: String { get set }
}

class MapInteractor: MapBusinessLogic, MapDataStore {
    var presenter: MapPresentationLogic?
    var worker = HotpepperWorker(hotpepper: HotpepperAPI())
    var urlString: String = ""
    private var initView: Bool = false
    
    // MARK: Init mapView
    
    func initMapView(request: Map.Init.Request) {
        if !initView {
            let response = Map.Init.Response(latitude: request.latitude, longitude: request.longitude)
            presenter?.presentInitMapView(response: response)
            initView = true
        }
    }
    
    // MARK: Search restaurants
    
    func searchRestaurants(request: Map.Search.Request) {
        worker.fetchRestaurants(latitude: request.latitude, longitude: request.longitude) { (restaurants, _) in
            let response = Map.Search.Response(restaurants: restaurants)
            self.presenter?.presentSearchedRestaurants(response: response)
        }
    }
    
    // MARK: Tap info window
    
    func fetchRestaurantInformation(request: Map.Fetch.Request) {
        urlString = request.urlString
        let response = Map.Fetch.Response()
        presenter?.presentFetchedRestaurantInformation(response: response)
    }
}
