//
//  MapModels.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/07.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Map {
    
    // MARK: Init mapView
    
    enum Init {
        struct Request {
            var latitude: Double
            var longitude: Double
        }
        struct Response {
            var latitude: Double
            var longitude: Double
        }
        struct ViewModel {
            var latitude: Double
            var longitude: Double
            var zoomLevel: Float
        }
    }
    
    // MARK: Search restaurants
    
    enum Search {
        struct Request {
            var latitude: Double
            var longitude: Double
        }
        struct Response {
            var restaurants: [Restaurant]
        }
        struct ViewModel {
            var restaurants: [Restaurant]
        }
    }
}
