//
//  MapRouter.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/07.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MapRoutingLogic {
    func routeToRestaurantInformation(segue: UIStoryboardSegue?)
}

protocol MapDataPassing {
    var dataStore: MapDataStore? { get }
}

class MapRouter: NSObject, MapRoutingLogic, MapDataPassing {
    weak var viewController: MapViewController?
    var dataStore: MapDataStore?
  
    // MARK: Routing
    
    func routeToRestaurantInformation(segue: UIStoryboardSegue?) {
      if let segue = segue {
        let destinationVC = segue.destination as! RestaurantInformationViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToRestaurantInformation(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "RestaurantInformationViewController") as! RestaurantInformationViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToRestaurantInformation(source: dataStore!, destination: &destinationDS)
        navigateToRestaurantInformation(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToRestaurantInformation(source: MapViewController, destination: RestaurantInformationViewController) {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToRestaurantInformation(source: MapDataStore, destination: inout RestaurantInformationDataStore) {
        destination.urlString = source.urlString
    }
}
