//
//  MapViewPresenter.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/07.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapViewPresentationLogic {
    func presentInitMapView(response: MapView.Init.Response)
    func presentSearchedRestaurants(response: MapView.Search.Response)
}

class MapViewPresenter: MapViewPresentationLogic {
    weak var viewController: MapViewDisplayLogic?
    private let zoomLevel: Float = 16.0
    
    // MARK: Present init mapView
    
    func presentInitMapView(response: MapView.Init.Response) {
        let latitude = response.latitude
        let longitude = response.longitude
        let viewModel = MapView.Init.ViewModel(latitude: latitude, longitude: longitude, zoomLevel: zoomLevel)
        viewController?.displayInitMap(viewModel: viewModel)
    }
    
    // MARK: Present searched restaurants
    
    func presentSearchedRestaurants(response: MapView.Search.Response) {
        let restaurants = response.restaurants
        let viewModel = MapView.Search.ViewModel(restaurants: restaurants)
        if restaurants.count > 0 {
            viewController?.displaySearchedSuccess(viewModel: viewModel)
            return
        }
        viewController?.displaySearchedFailure(viewModel: viewModel)
    }
}
