//
//  MapWorker.swift
//  CleanFoodLogger
//
//  Created by Takahiro Kato on 2017/10/07.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MapWorker {
    func doSomeWork() {
    }
}
